[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/fund-memo"
  to = "https://pwv.notion.site/PWV-Fund-Memo-116b3e27e9b580cfb085e18e4281e407"
  status = 301
  force = true
  