[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/fund-memo"
  to = "https://fund.pwv.com/"
  status = 301
  force = true

[[redirects]]
  from = "/teaser-deck"
  to = "https://pwv.docsend.com/v/mvzp8/pwv-teaser-deck"
  status = 301
  force = true

[[redirects]]
  from = "/teaserdeck"
  to = "https://pwv.docsend.com/v/mvzp8/pwv-teaser-deck"
  status = 301
  force = true
  
[[redirects]]
  from = "/data-room"
  to = "https://pwv.docsend.com/view/s/4iy3dfkzkgffqt4p"
  status = 301
  force = true
  
[[redirects]]
  from = "/dataroom"
  to = "https://pwv.docsend.com/view/s/4iy3dfkzkgffqt4p"
  status = 301
  force = true
