[build]
  command = "pnpm build"
  publish = "dist"

[dev]
  command = "pnpm dev"
  targetPort = 5137

[[redirects]]
  from = "/fund-memo"
  to = "https://redwoodjs.notion.site/PWV-Fund-Memo-10bb3e27e9b58027bb89fe94717cf9ac"
  status = 301
  force = true
